export const flashCardsData = [
    {
        id: 1,
        term: "Algorithm",
        definition: "A step-by-step procedure or set of rules to be followed in calculations or problem-solving.",
        subtopic: "Fundamentals",
        question: "Which of the following properties is NOT required for an algorithm to be valid?",
        options: ["Finiteness", "Definiteness", "Effectiveness", "Ambiguity"],
        correctAnswer: 3
    },
    {
        id: 2,
        term: "Compiler",
        definition: "A program that translates source code written in a high-level language into machine code.",
        subtopic: "Systems",
        question: "What is the intermediate code generated by a Java compiler called?",
        options: ["Machine Code", "Bytecode", "Assembly", "Source Code"],
        correctAnswer: 1
    },
    {
        id: 3,
        term: "Interpreter",
        definition: "A program that executes instructions written in a programming language directly, line by line.",
        subtopic: "Systems",
        question: "Which of the following languages is primarily interpreted?",
        options: ["C++", "Python", "Rust", "Go"],
        correctAnswer: 1
    },
    {
        id: 4,
        term: "Variable",
        definition: "A storage location paired with an associated symbolic name, which contains some known or unknown quantity of information.",
        subtopic: "Fundamentals",
        question: "In statically typed languages, a variable's type works how?",
        options: ["Can change at runtime", "Is determined at compile time", "Is optional", "Does not exist"],
        correctAnswer: 1
    },
    {
        id: 5,
        term: "Polymorphism",
        definition: "OOP concept where a single interface represents different underlying forms (data types).",
        subtopic: "OOP",
        question: "Which type of polymorphism is achieved via method overloading?",
        options: ["Runtime", "Compile-time", "Ad-hoc", "Coercion"],
        correctAnswer: 1
    },
    {
        id: 6,
        term: "Encapsulation",
        definition: "Bundling of data with the methods that operate on that data.",
        subtopic: "OOP",
        question: "What access modifier best supports encapsulation by hiding data?",
        options: ["Public", "Private", "Protected", "Static"],
        correctAnswer: 1
    },
    {
        id: 7,
        term: "Recursion",
        definition: "A method where the solution to a problem depends on solutions to smaller instances of the same problem.",
        subtopic: "Data Structures",
        question: "What is mandatory to prevent a recursive function from running indefinitely?",
        options: ["Base Case", "Recursive Case", "Loop", "Global Variable"],
        correctAnswer: 0
    },
    {
        id: 8,
        term: "Array",
        definition: "A data structure consisting of a collection of elements, each identified by at least one array index or key.",
        subtopic: "Data Structures",
        question: "What is the time complexity to access an element in an array by index?",
        options: ["O(n)", "O(log n)", "O(1)", "O(n^2)"],
        correctAnswer: 2
    },
    {
        id: 9,
        term: "Linked List",
        definition: "A linear collection of data elements whose order is not given by their physical placement in memory.",
        subtopic: "Data Structures",
        question: "Compared to arrays, what is a primary disadvantage of linked lists?",
        options: ["Dynamic size", "Ease of insertion", "Random access is slow", "Memory efficiency"],
        correctAnswer: 2
    },
    {
        id: 10,
        term: "Stack",
        definition: "A linear data structure which follows a particular order in which the operations are performed (LIFO).",
        subtopic: "Data Structures",
        question: "Which application typically uses a stack?",
        options: ["Print Queue", "Function Call Management", "Disk Scheduling", "Network Routing"],
        correctAnswer: 1
    },
    {
        id: 11,
        term: "Queue",
        definition: "A linear structure which follows a particular order in which the operations are performed (FIFO).",
        subtopic: "Data Structures",
        question: "Which data structure is best for a breadth-first search (BFS)?",
        options: ["Stack", "Queue", "Tree", "Graph"],
        correctAnswer: 1
    },
    {
        id: 12,
        term: "Binary Tree",
        definition: "A tree data structure in which each node has at most two children.",
        subtopic: "Data Structures",
        question: "What is the maximum number of nodes at level 'L' in a binary tree?",
        options: ["2^L", "2^(L-1)", "2L", "L^2"],
        correctAnswer: 0
    },
    {
        id: 13,
        term: "Hash Table",
        definition: "A data structure that implements an associative array abstract data type, mapping keys to values.",
        subtopic: "Data Structures",
        question: "What handles collisions in a Hash Table?",
        options: ["Chaining", "Stacking", "Queueing", "Sorting"],
        correctAnswer: 0
    },
    {
        id: 14,
        term: "Graph",
        definition: "A non-linear data structure consisting of nodes (vertices) and edges.",
        subtopic: "Data Structures",
        question: "Which algorithm finds the shortest path in an unweighted graph?",
        options: ["Dijkstra", "BFS", "DFS", "Prim's"],
        correctAnswer: 1
    },
    {
        id: 15,
        term: "Heap",
        definition: "A specialized tree-based data structure which is essentially an almost complete tree that satisfies the heap property.",
        subtopic: "Data Structures",
        question: "What is the time complexity to extract the maximum element from a Max-Heap?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        correctAnswer: 1
    }
];

export const puzzleData = [
    { id: '1', term: "Bug", match: "Error in program" },
    { id: '2', term: "Binary", match: "0s and 1s" },
    { id: '3', term: "CPU", match: "Brain of computer" },
    { id: '4', term: "Loop", match: "Repetition" },
    { id: '5', term: "RAM", match: "Volatile Memory" },
    { id: '6', term: "SSD", match: "Solid State Drive" },
    { id: '7', term: "GUI", match: "Graphical User Interface" },
    { id: '8', term: "OS", match: "Operating System" },
    { id: '9', term: "IP", match: "Internet Protocol" },
    { id: '10', term: "URL", match: "Web Address" },
    { id: '11', term: "HTML", match: "Web Structure" },
    { id: '12', term: "CSS", match: "Web Styling" },
    { id: '13', term: "SQL", match: "Database Query" },
    { id: '14', term: "API", match: "Software Interface" },
    { id: '15', term: "IDE", match: "Coding Environment" }
];

export const debuggerData = [
    {
        id: 1,
        title: "Infinite Loop",
        snippet: "while (x > 0) {\n  console.log(x);\n  // Missing decrement\n}",
        options: ["Syntax Error", "Infinite Loop", "Logic Error", "Runtime Error"],
        correct: 1,
        explanation: "The variable 'x' is never modified, so the condition x > 0 remains true forever."
    },
    {
        id: 2,
        title: "Off By One",
        snippet: "let arr = [1, 2, 3];\nfor (let i = 0; i <= arr.length; i++) {\n  console.log(arr[i]);\n}",
        options: ["Array out of bounds", "Syntax Error", "Compilation Error", "None"],
        correct: 0,
        explanation: "The loop condition i <= arr.length causes the loop to access a non-existent index (arr[3])."
    },
    {
        id: 3,
        title: "Python Indentation",
        snippet: "def my_func():\nprint('Hello')\n  print('World')",
        options: ["Logic Error", "IndentationError", "NameError", "Runtime Error"],
        correct: 1,
        explanation: "In Python, consistent indentation is required to define code blocks."
    },
    {
        id: 4,
        title: "Java Null Pointer",
        snippet: "String s = null;\nSystem.out.println(s.length());",
        options: ["NullPointerException", "ArrayIndexOutOfBounds", "ClassCastException", "None"],
        correct: 0,
        explanation: "Calling a method (.length()) on a null reference throws a NullPointerException."
    },
    {
        id: 5,
        title: "C++ Missing Semicolon",
        snippet: "int main() {\n  cout << 'Hello'\n  return 0;\n}",
        options: ["Runtime Error", "Logic Error", "Syntax Error", "Linker Error"],
        correct: 2,
        explanation: "C++ statements must end with a semicolon."
    }
];

export const mistakeFinderData = [
    {
        id: 1,
        scenario: "You want to check if a variable 'x' is equal to 10.",
        code: "if (x = 10) { ... }",
        error: "Assignment (=) used instead of comparison (==)",
        type: "Logic Error"
    },
    {
        id: 2,
        scenario: "You want to loop 5 times, from 0 to 4.",
        code: "for (int i = 0; i < 5; i--)",
        error: "Decrementing i (i--) instead of incrementing",
        type: "Logic Error"
    },
    {
        id: 3,
        scenario: "Calculating average of a and b.",
        code: "double avg = a + b / 2;",
        error: "Missing parentheses: (a + b) / 2",
        type: "Logic Error"
    },
    {
        id: 4,
        scenario: "Accessing the last element of an array of size 10.",
        code: "int val = arr[10];",
        error: "Index 10 is out of bounds (0-9 are valid)",
        type: "Runtime Error"
    },
    {
        id: 5,
        scenario: "Checking if a string is empty in Java.",
        code: "if (str == \"\")",
        error: "Using == compares references, use .equals()",
        type: "Logic Error"
    }
];
